# Generated by Django 3.2 on 2023-10-24 10:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(default='T5ZGCYCX1IQ3', max_length=12, unique=True)),
                ('purpose', models.TextField()),
                ('color', models.CharField(max_length=7)),
                ('area', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ceiling_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_draft', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_type', models.CharField(choices=[('left', 'Левый'), ('right', 'Правый')], max_length=10)),
                ('image', models.ImageField(upload_to='visualizations/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_type', models.CharField(choices=[('left', 'Левый'), ('right', 'Правый')], max_length=10)),
                ('image', models.ImageField(upload_to='plans/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_type', models.CharField(choices=[('3d_visualization', '3D Визуализация'), ('room_data', 'Исходные данные помещения'), ('furniture_layout', 'План расстановки мебели'), ('furniture_specifications', 'Спецификации мебели и сантехники'), ('lighting_equipment_layout', 'План расстановки осветительного оборудования'), ('lighting_device_attachment', 'План привязки осветительных приборов'), ('socket_layout', 'План расстановки розеток'), ('floor_covering_layout', 'План напольных покрытий'), ('ceiling_layout', 'План потолка'), ('wall_finishing_layout', 'Развертки стен с отделкой'), ('finishing_materials_specifications', 'Спецификации отделочных материалов'), ('custom_furniture', 'Мебель индивидуального изготовления')], max_length=50)),
                ('file', models.FileField(upload_to='details/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'pdf'])])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('project', 'view_type'), name='unique_project_viewtype_for_plan'),
        ),
    ]
