# Generated by Django 3.2 on 2023-10-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='article',
            field=models.CharField(default='FI0KGR2OVPTI', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
